### ISSUE TITLE
[feature]: Support cancellation

### ISSUE THREAD

**Issue by dankeboy36** [TypeFox/vscode-messenger#16]
Thanks for the lib ❤️ 

Support cancellation. Maybe with `AbortSignal`. It's available in the browser and from Node.js 15+: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal#browser_compatibility

```ts
import { isAbortError } from 'abort-controller-x';
import { HOST_EXTENSION, RequestType } from 'vscode-messenger-common';
import { Messenger } from 'vscode-messenger-webview';

(async () => {
    try {
        const messenger: Messenger = undefined;
        type Params = Record<string, string>;
        const requestType: RequestType<Params, readonly unknown[]> = { method: 'long-running' };
        const myParams: Params = { foo: 'bar' };
        const abortController = new AbortController();
        const { signal } = abortController;
        const result = await messenger.sendRequest(requestType, HOST_EXTENSION, myParams, { signal });
        return result;
    } catch (err) {
        if (isAbortError(err)) {
            return [];
        }
        throw err;
    }
})();
```

**Comment by dhuebner** [comment]
@dankeboy36 
Thanks for nice feature request!
To make it clear: you just want to cancel/reject the pending request and not the handler that is running on extension side?

**Comment by dhuebner** [comment]
@dankeboy36 
Just sending `{signal}` with a request will not work, we need a separate communication channel with a built-in `NotificationType` to cancel the running handler on the "other" side. 
I will draft an API for that next days, stay tuned.

**Comment by dhuebner** [comment]
@dankeboy36 

Request  handler now has an additional parameter `cancelIndicator: CancelIndicator` 
```ts
export type RequestHandler<P, R> =
    (params: P, sender: MessageParticipant, cancelIndicator: CancelIndicator) => HandlerResult<R>;
```

CancelIndicator can be asked for the cancelation state or one can set the callback function `onCancel `
```ts
export interface CancelIndicator {
    isCanceled(): boolean;
    onCancel: ((reason: string) => void) | undefined;
}
```

On the sender side `sendRequest` method now allows to pass a `Cancelable` instance which allows to call `cancel(reason: string)` . Calling `cancel` will then activate the CancelIndicator. The internal pending request will be rejected. 

Simple timeout example: 
```js
const cancelable = new vscode_messenger_common.Cancelable();
setTimeout(() => cancelable.cancel('Timeout: 1 sec'), 1000);
const colors = await messenger.sendRequest(
    { method: 'availableColor' },
    { type: 'extension' },
    '', 
    cancelable
);
```

The code is currently on a branch `dhuebner/canelPendingRequest-16`, do you have a possibility to try it out locally?

**Comment by dankeboy36** [comment]
Absolutely, I have been monitoring your changes. Very nice, thank you! 

Is there a reason this lib invents its own `Cancelable` type instead of `AbortSignal`?
